"""
AstroOS -- 112 Sukshmamsha (Pada-112) Naming and Classification (Sarvatobhadra Chakra)

Reference:
- Classical Sarvatobhadra Chakra (SBC) 28-Nakshatra x 4 Padas = 112 Sukshmamshas
- Source Workbook: 2026-07-20_SarvatobhadraChakra_Vedhas_rev3.xlsm (tblSukhmansha, modSBC_Pada112Map)

Numbering convention:
- Pada 1 = Krittika-1
- Padas 1 to 112 wrap cyclically through Bharani-4 (112).
- Includes Abhijit Nakshatra (4 Padas: 77 to 80, between Uttara Ashadha and Sravana).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Final, Optional


class SukshmamshaNature(str, Enum):
    """Predictive valence and nature of the 112 Sukshmamsha divisions."""
    AUSPICIOUS = "auspicious"
    INAUSPICIOUS = "inauspicious"
    MIXED = "mixed"


@dataclass(frozen=True)
class SukshmamshaInfo:
    """Attributes and classical classification of one of the 112 Sukshmamshas."""
    index: int
    nakshatra: str
    pada: int
    nakshatra_pada: str
    name_sa: str
    name_en: str
    nature: SukshmamshaNature
    meaning: str


SUKSHMAMSHA_BY_INDEX: Final[dict[int, SukshmamshaInfo]] = {
    1: SukshmamshaInfo(
        index=1,
        nakshatra='Krittika',
        pada=1,
        nakshatra_pada='Krittika-1',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth, riches",
    ),
    2: SukshmamshaInfo(
        index=2,
        nakshatra='Krittika',
        pada=2,
        nakshatra_pada='Krittika-2',
        name_sa='पापांश',
        name_en='Pāpāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sin, evil, adversity",
    ),
    3: SukshmamshaInfo(
        index=3,
        nakshatra='Krittika',
        pada=3,
        nakshatra_pada='Krittika-3',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce, intense",
    ),
    4: SukshmamshaInfo(
        index=4,
        nakshatra='Krittika',
        pada=4,
        nakshatra_pada='Krittika-4',
        name_sa='उत्कृष्टांश',
        name_en='Utkṛṣṭāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Excellent, eminent",
    ),
    5: SukshmamshaInfo(
        index=5,
        nakshatra='Rohini',
        pada=1,
        nakshatra_pada='Rohini-1',
        name_sa='सेनांश',
        name_en='Senāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Army, military strength",
    ),
    6: SukshmamshaInfo(
        index=6,
        nakshatra='Rohini',
        pada=2,
        nakshatra_pada='Rohini-2',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment, pleasures",
    ),
    7: SukshmamshaInfo(
        index=7,
        nakshatra='Rohini',
        pada=3,
        nakshatra_pada='Rohini-3',
        name_sa='विद्यांश',
        name_en='Vidyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Learning, knowledge",
    ),
    8: SukshmamshaInfo(
        index=8,
        nakshatra='Rohini',
        pada=4,
        nakshatra_pada='Rohini-4',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth",
    ),
    9: SukshmamshaInfo(
        index=9,
        nakshatra='Mrigashira',
        pada=1,
        nakshatra_pada='Mrigashira-1',
        name_sa='राज्यांश',
        name_en='Rājyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Kingdom, authority",
    ),
    10: SukshmamshaInfo(
        index=10,
        nakshatra='Mrigashira',
        pada=2,
        nakshatra_pada='Mrigashira-2',
        name_sa='चंद्रांश',
        name_en='Candrāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Moon, calmness",
    ),
    11: SukshmamshaInfo(
        index=11,
        nakshatra='Mrigashira',
        pada=3,
        nakshatra_pada='Mrigashira-3',
        name_sa='अभयांश',
        name_en='Abhayāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fearlessness, protection",
    ),
    12: SukshmamshaInfo(
        index=12,
        nakshatra='Mrigashira',
        pada=4,
        nakshatra_pada='Mrigashira-4',
        name_sa='नीचांश',
        name_en='Nīcāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Lowly, fallen",
    ),
    13: SukshmamshaInfo(
        index=13,
        nakshatra='Ardra',
        pada=1,
        nakshatra_pada='Ardra-1',
        name_sa='कृपांश',
        name_en='Kṛpāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Compassion, grace",
    ),
    14: SukshmamshaInfo(
        index=14,
        nakshatra='Ardra',
        pada=2,
        nakshatra_pada='Ardra-2',
        name_sa='तस्करांश',
        name_en='Taskarāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Thief, stealth",
    ),
    15: SukshmamshaInfo(
        index=15,
        nakshatra='Ardra',
        pada=3,
        nakshatra_pada='Ardra-3',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    16: SukshmamshaInfo(
        index=16,
        nakshatra='Ardra',
        pada=4,
        nakshatra_pada='Ardra-4',
        name_sa='उत्कृष्टांश',
        name_en='Utkṛṣṭāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Excellent",
    ),
    17: SukshmamshaInfo(
        index=17,
        nakshatra='Punarvasu',
        pada=1,
        nakshatra_pada='Punarvasu-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Born, produced, arising",
    ),
    18: SukshmamshaInfo(
        index=18,
        nakshatra='Punarvasu',
        pada=2,
        nakshatra_pada='Punarvasu-2',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment",
    ),
    19: SukshmamshaInfo(
        index=19,
        nakshatra='Punarvasu',
        pada=3,
        nakshatra_pada='Punarvasu-3',
        name_sa='सौम्यांश',
        name_en='Saumyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Gentle, benefic",
    ),
    20: SukshmamshaInfo(
        index=20,
        nakshatra='Punarvasu',
        pada=4,
        nakshatra_pada='Punarvasu-4',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth",
    ),
    21: SukshmamshaInfo(
        index=21,
        nakshatra='Pushya',
        pada=1,
        nakshatra_pada='Pushya-1',
        name_sa='भूपांश',
        name_en='Bhūpāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="King, ruler",
    ),
    22: SukshmamshaInfo(
        index=22,
        nakshatra='Pushya',
        pada=2,
        nakshatra_pada='Pushya-2',
        name_sa='सौख्यांश',
        name_en='Saukhyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Comfort, happiness",
    ),
    23: SukshmamshaInfo(
        index=23,
        nakshatra='Pushya',
        pada=3,
        nakshatra_pada='Pushya-3',
        name_sa='शूरांश',
        name_en='Śūrāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Heroic, valiant",
    ),
    24: SukshmamshaInfo(
        index=24,
        nakshatra='Pushya',
        pada=4,
        nakshatra_pada='Pushya-4',
        name_sa='दारिद्र्यांश',
        name_en='Dāridryāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Poverty",
    ),
    25: SukshmamshaInfo(
        index=25,
        nakshatra='Aslesha',
        pada=1,
        nakshatra_pada='Aslesha-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    26: SukshmamshaInfo(
        index=26,
        nakshatra='Aslesha',
        pada=2,
        nakshatra_pada='Aslesha-2',
        name_sa='पापांश',
        name_en='Pāpāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sinful",
    ),
    27: SukshmamshaInfo(
        index=27,
        nakshatra='Aslesha',
        pada=3,
        nakshatra_pada='Aslesha-3',
        name_sa='क्रोधांश',
        name_en='Krodhāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Anger",
    ),
    28: SukshmamshaInfo(
        index=28,
        nakshatra='Aslesha',
        pada=4,
        nakshatra_pada='Aslesha-4',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    29: SukshmamshaInfo(
        index=29,
        nakshatra='Makha',
        pada=1,
        nakshatra_pada='Makha-1',
        name_sa='सेनांश',
        name_en='Senāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Army",
    ),
    30: SukshmamshaInfo(
        index=30,
        nakshatra='Makha',
        pada=2,
        nakshatra_pada='Makha-2',
        name_sa='न्यायांश',
        name_en='Nyāyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Justice",
    ),
    31: SukshmamshaInfo(
        index=31,
        nakshatra='Makha',
        pada=3,
        nakshatra_pada='Makha-3',
        name_sa='विचक्षणांश',
        name_en='Vicakṣaṇāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wise, discerning",
    ),
    32: SukshmamshaInfo(
        index=32,
        nakshatra='Makha',
        pada=4,
        nakshatra_pada='Makha-4',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth",
    ),
    33: SukshmamshaInfo(
        index=33,
        nakshatra='Purva Phalguni',
        pada=1,
        nakshatra_pada='Purva Phalguni-1',
        name_sa='राज्यांश',
        name_en='Rājyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Authority",
    ),
    34: SukshmamshaInfo(
        index=34,
        nakshatra='Purva Phalguni',
        pada=2,
        nakshatra_pada='Purva Phalguni-2',
        name_sa='नपुंसकांश',
        name_en='Napuṁsakāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Neuter, impotent",
    ),
    35: SukshmamshaInfo(
        index=35,
        nakshatra='Purva Phalguni',
        pada=3,
        nakshatra_pada='Purva Phalguni-3',
        name_sa='अभयांश',
        name_en='Abhayāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fearlessness",
    ),
    36: SukshmamshaInfo(
        index=36,
        nakshatra='Purva Phalguni',
        pada=4,
        nakshatra_pada='Purva Phalguni-4',
        name_sa='दारिद्र्यांश',
        name_en='Dāridryāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Poverty",
    ),
    37: SukshmamshaInfo(
        index=37,
        nakshatra='Uttara Phalguni',
        pada=1,
        nakshatra_pada='Uttara Phalguni-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    38: SukshmamshaInfo(
        index=38,
        nakshatra='Uttara Phalguni',
        pada=2,
        nakshatra_pada='Uttara Phalguni-2',
        name_sa='पापांश',
        name_en='Pāpāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sinful",
    ),
    39: SukshmamshaInfo(
        index=39,
        nakshatra='Uttara Phalguni',
        pada=3,
        nakshatra_pada='Uttara Phalguni-3',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    40: SukshmamshaInfo(
        index=40,
        nakshatra='Uttara Phalguni',
        pada=4,
        nakshatra_pada='Uttara Phalguni-4',
        name_sa='शुभांश',
        name_en='Śubhāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Auspicious",
    ),
    41: SukshmamshaInfo(
        index=41,
        nakshatra='Hasta',
        pada=1,
        nakshatra_pada='Hasta-1',
        name_sa='बलिष्ठांश',
        name_en='Baliṣṭhāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Strong, mighty",
    ),
    42: SukshmamshaInfo(
        index=42,
        nakshatra='Hasta',
        pada=2,
        nakshatra_pada='Hasta-2',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment",
    ),
    43: SukshmamshaInfo(
        index=43,
        nakshatra='Hasta',
        pada=3,
        nakshatra_pada='Hasta-3',
        name_sa='पण्डितांश',
        name_en='Paṇḍitāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Scholar",
    ),
    44: SukshmamshaInfo(
        index=44,
        nakshatra='Hasta',
        pada=4,
        nakshatra_pada='Hasta-4',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth",
    ),
    45: SukshmamshaInfo(
        index=45,
        nakshatra='Chitra',
        pada=1,
        nakshatra_pada='Chitra-1',
        name_sa='नृपांश',
        name_en='Nṛpāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="King",
    ),
    46: SukshmamshaInfo(
        index=46,
        nakshatra='Chitra',
        pada=2,
        nakshatra_pada='Chitra-2',
        name_sa='नपुंसकांश',
        name_en='Napuṁsakāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Neuter",
    ),
    47: SukshmamshaInfo(
        index=47,
        nakshatra='Chitra',
        pada=3,
        nakshatra_pada='Chitra-3',
        name_sa='अभयांश',
        name_en='Abhayāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fearlessness",
    ),
    48: SukshmamshaInfo(
        index=48,
        nakshatra='Chitra',
        pada=4,
        nakshatra_pada='Chitra-4',
        name_sa='दारिद्र्यांश',
        name_en='Dāridryāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Poverty",
    ),
    49: SukshmamshaInfo(
        index=49,
        nakshatra='Swati',
        pada=1,
        nakshatra_pada='Swati-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    50: SukshmamshaInfo(
        index=50,
        nakshatra='Swati',
        pada=2,
        nakshatra_pada='Swati-2',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth",
    ),
    51: SukshmamshaInfo(
        index=51,
        nakshatra='Swati',
        pada=3,
        nakshatra_pada='Swati-3',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    52: SukshmamshaInfo(
        index=52,
        nakshatra='Swati',
        pada=4,
        nakshatra_pada='Swati-4',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    53: SukshmamshaInfo(
        index=53,
        nakshatra='Visakha',
        pada=1,
        nakshatra_pada='Visakha-1',
        name_sa='सौख्यांश',
        name_en='Saukhyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Comfort",
    ),
    54: SukshmamshaInfo(
        index=54,
        nakshatra='Visakha',
        pada=2,
        nakshatra_pada='Visakha-2',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment",
    ),
    55: SukshmamshaInfo(
        index=55,
        nakshatra='Visakha',
        pada=3,
        nakshatra_pada='Visakha-3',
        name_sa='सौम्यांश',
        name_en='Saumyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Gentle",
    ),
    56: SukshmamshaInfo(
        index=56,
        nakshatra='Visakha',
        pada=4,
        nakshatra_pada='Visakha-4',
        name_sa='अर्थांश',
        name_en='Arthāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Purpose, wealth",
    ),
    57: SukshmamshaInfo(
        index=57,
        nakshatra='Anuradha',
        pada=1,
        nakshatra_pada='Anuradha-1',
        name_sa='नृपांश',
        name_en='Nṛpāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="King",
    ),
    58: SukshmamshaInfo(
        index=58,
        nakshatra='Anuradha',
        pada=2,
        nakshatra_pada='Anuradha-2',
        name_sa='नपुंसकांश',
        name_en='Napuṁsakāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Neuter",
    ),
    59: SukshmamshaInfo(
        index=59,
        nakshatra='Anuradha',
        pada=3,
        nakshatra_pada='Anuradha-3',
        name_sa='अभयांश',
        name_en='Abhayāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fearlessness",
    ),
    60: SukshmamshaInfo(
        index=60,
        nakshatra='Anuradha',
        pada=4,
        nakshatra_pada='Anuradha-4',
        name_sa='नीचांश',
        name_en='Nīcāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Lowly",
    ),
    61: SukshmamshaInfo(
        index=61,
        nakshatra='Jyestha',
        pada=1,
        nakshatra_pada='Jyestha-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    62: SukshmamshaInfo(
        index=62,
        nakshatra='Jyestha',
        pada=2,
        nakshatra_pada='Jyestha-2',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    63: SukshmamshaInfo(
        index=63,
        nakshatra='Jyestha',
        pada=3,
        nakshatra_pada='Jyestha-3',
        name_sa='पापांश',
        name_en='Pāpāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sinful",
    ),
    64: SukshmamshaInfo(
        index=64,
        nakshatra='Jyestha',
        pada=4,
        nakshatra_pada='Jyestha-4',
        name_sa='शुभांश',
        name_en='Śubhāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Auspicious",
    ),
    65: SukshmamshaInfo(
        index=65,
        nakshatra='Moola',
        pada=1,
        nakshatra_pada='Moola-1',
        name_sa='तस्करांश',
        name_en='Taskarāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Thief",
    ),
    66: SukshmamshaInfo(
        index=66,
        nakshatra='Moola',
        pada=2,
        nakshatra_pada='Moola-2',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment",
    ),
    67: SukshmamshaInfo(
        index=67,
        nakshatra='Moola',
        pada=3,
        nakshatra_pada='Moola-3',
        name_sa='विचक्षणांश',
        name_en='Vicakṣaṇāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Discerning",
    ),
    68: SukshmamshaInfo(
        index=68,
        nakshatra='Moola',
        pada=4,
        nakshatra_pada='Moola-4',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth",
    ),
    69: SukshmamshaInfo(
        index=69,
        nakshatra='Purva Asadha',
        pada=1,
        nakshatra_pada='Purva Asadha-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    70: SukshmamshaInfo(
        index=70,
        nakshatra='Purva Asadha',
        pada=2,
        nakshatra_pada='Purva Asadha-2',
        name_sa='अभयांश',
        name_en='Abhayāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fearlessness",
    ),
    71: SukshmamshaInfo(
        index=71,
        nakshatra='Purva Asadha',
        pada=3,
        nakshatra_pada='Purva Asadha-3',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment",
    ),
    72: SukshmamshaInfo(
        index=72,
        nakshatra='Purva Asadha',
        pada=4,
        nakshatra_pada='Purva Asadha-4',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    73: SukshmamshaInfo(
        index=73,
        nakshatra='Uttara Asadha',
        pada=1,
        nakshatra_pada='Uttara Asadha-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    74: SukshmamshaInfo(
        index=74,
        nakshatra='Uttara Asadha',
        pada=2,
        nakshatra_pada='Uttara Asadha-2',
        name_sa='पापांश',
        name_en='Pāpāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sinful",
    ),
    75: SukshmamshaInfo(
        index=75,
        nakshatra='Uttara Asadha',
        pada=3,
        nakshatra_pada='Uttara Asadha-3',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    76: SukshmamshaInfo(
        index=76,
        nakshatra='Uttara Asadha',
        pada=4,
        nakshatra_pada='Uttara Asadha-4',
        name_sa='शोभनांश',
        name_en='Śobhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Beautiful, splendid",
    ),
    77: SukshmamshaInfo(
        index=77,
        nakshatra='Abhijit',
        pada=1,
        nakshatra_pada='Abhijit-1',
        name_sa='मङ्गलांश',
        name_en='Maṅgalāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Auspicious, fortunate",
    ),
    78: SukshmamshaInfo(
        index=78,
        nakshatra='Abhijit',
        pada=2,
        nakshatra_pada='Abhijit-2',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment",
    ),
    79: SukshmamshaInfo(
        index=79,
        nakshatra='Abhijit',
        pada=3,
        nakshatra_pada='Abhijit-3',
        name_sa='विचक्षणांश',
        name_en='Vicakṣaṇāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Discerning",
    ),
    80: SukshmamshaInfo(
        index=80,
        nakshatra='Abhijit',
        pada=4,
        nakshatra_pada='Abhijit-4',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth",
    ),
    81: SukshmamshaInfo(
        index=81,
        nakshatra='Sravana',
        pada=1,
        nakshatra_pada='Sravana-1',
        name_sa='नृपांश',
        name_en='Nṛpāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="King",
    ),
    82: SukshmamshaInfo(
        index=82,
        nakshatra='Sravana',
        pada=2,
        nakshatra_pada='Sravana-2',
        name_sa='सौम्यांश',
        name_en='Saumyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Gentle",
    ),
    83: SukshmamshaInfo(
        index=83,
        nakshatra='Sravana',
        pada=3,
        nakshatra_pada='Sravana-3',
        name_sa='अभयांश',
        name_en='Abhayāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fearlessness",
    ),
    84: SukshmamshaInfo(
        index=84,
        nakshatra='Sravana',
        pada=4,
        nakshatra_pada='Sravana-4',
        name_sa='क्रूरांश',
        name_en='Krūrāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Cruel, harsh",
    ),
    85: SukshmamshaInfo(
        index=85,
        nakshatra='Dhanistha',
        pada=1,
        nakshatra_pada='Dhanistha-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    86: SukshmamshaInfo(
        index=86,
        nakshatra='Dhanistha',
        pada=2,
        nakshatra_pada='Dhanistha-2',
        name_sa='पापांश',
        name_en='Pāpāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sinful",
    ),
    87: SukshmamshaInfo(
        index=87,
        nakshatra='Dhanistha',
        pada=3,
        nakshatra_pada='Dhanistha-3',
        name_sa='भयांश',
        name_en='Bhayāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fear",
    ),
    88: SukshmamshaInfo(
        index=88,
        nakshatra='Dhanistha',
        pada=4,
        nakshatra_pada='Dhanistha-4',
        name_sa='सौम्यांश',
        name_en='Saumyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Gentle",
    ),
    89: SukshmamshaInfo(
        index=89,
        nakshatra='Satabhisaj',
        pada=1,
        nakshatra_pada='Satabhisaj-1',
        name_sa='सेनांश',
        name_en='Senāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Army",
    ),
    90: SukshmamshaInfo(
        index=90,
        nakshatra='Satabhisaj',
        pada=2,
        nakshatra_pada='Satabhisaj-2',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment",
    ),
    91: SukshmamshaInfo(
        index=91,
        nakshatra='Satabhisaj',
        pada=3,
        nakshatra_pada='Satabhisaj-3',
        name_sa='विचक्षणांश',
        name_en='Vicakṣaṇāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Discerning",
    ),
    92: SukshmamshaInfo(
        index=92,
        nakshatra='Satabhisaj',
        pada=4,
        nakshatra_pada='Satabhisaj-4',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth",
    ),
    93: SukshmamshaInfo(
        index=93,
        nakshatra='Purva Bhadrapada',
        pada=1,
        nakshatra_pada='Purva Bhadrapada-1',
        name_sa='तीक्ष्णांश',
        name_en='Tīkṣṇāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sharp, piercing",
    ),
    94: SukshmamshaInfo(
        index=94,
        nakshatra='Purva Bhadrapada',
        pada=2,
        nakshatra_pada='Purva Bhadrapada-2',
        name_sa='सौम्यांश',
        name_en='Saumyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Gentle",
    ),
    95: SukshmamshaInfo(
        index=95,
        nakshatra='Purva Bhadrapada',
        pada=3,
        nakshatra_pada='Purva Bhadrapada-3',
        name_sa='अभयांश',
        name_en='Abhayāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fearlessness",
    ),
    96: SukshmamshaInfo(
        index=96,
        nakshatra='Purva Bhadrapada',
        pada=4,
        nakshatra_pada='Purva Bhadrapada-4',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    97: SukshmamshaInfo(
        index=97,
        nakshatra='Uttara Bhadrapada',
        pada=1,
        nakshatra_pada='Uttara Bhadrapada-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    98: SukshmamshaInfo(
        index=98,
        nakshatra='Uttara Bhadrapada',
        pada=2,
        nakshatra_pada='Uttara Bhadrapada-2',
        name_sa='पापांश',
        name_en='Pāpāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sinful",
    ),
    99: SukshmamshaInfo(
        index=99,
        nakshatra='Uttara Bhadrapada',
        pada=3,
        nakshatra_pada='Uttara Bhadrapada-3',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    100: SukshmamshaInfo(
        index=100,
        nakshatra='Uttara Bhadrapada',
        pada=4,
        nakshatra_pada='Uttara Bhadrapada-4',
        name_sa='शोभनांश',
        name_en='Śobhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Beautiful, splendid",
    ),
    101: SukshmamshaInfo(
        index=101,
        nakshatra='Revati',
        pada=1,
        nakshatra_pada='Revati-1',
        name_sa='तस्करांश',
        name_en='Taskarāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Thief",
    ),
    102: SukshmamshaInfo(
        index=102,
        nakshatra='Revati',
        pada=2,
        nakshatra_pada='Revati-2',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment",
    ),
    103: SukshmamshaInfo(
        index=103,
        nakshatra='Revati',
        pada=3,
        nakshatra_pada='Revati-3',
        name_sa='पण्डितांश',
        name_en='Paṇḍitāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Scholar",
    ),
    104: SukshmamshaInfo(
        index=104,
        nakshatra='Revati',
        pada=4,
        nakshatra_pada='Revati-4',
        name_sa='धनांश',
        name_en='Dhanāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Wealth",
    ),
    105: SukshmamshaInfo(
        index=105,
        nakshatra='Aswini',
        pada=1,
        nakshatra_pada='Aswini-1',
        name_sa='नृपांश',
        name_en='Nṛpāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="King",
    ),
    106: SukshmamshaInfo(
        index=106,
        nakshatra='Aswini',
        pada=2,
        nakshatra_pada='Aswini-2',
        name_sa='भोग्यांश',
        name_en='Bhogyāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Enjoyment",
    ),
    107: SukshmamshaInfo(
        index=107,
        nakshatra='Aswini',
        pada=3,
        nakshatra_pada='Aswini-3',
        name_sa='अभयांश',
        name_en='Abhayāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fearlessness",
    ),
    108: SukshmamshaInfo(
        index=108,
        nakshatra='Aswini',
        pada=4,
        nakshatra_pada='Aswini-4',
        name_sa='पापांश',
        name_en='Pāpāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sinful",
    ),
    109: SukshmamshaInfo(
        index=109,
        nakshatra='Bharani',
        pada=1,
        nakshatra_pada='Bharani-1',
        name_sa='उत्पन्नांश',
        name_en='Utpannāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Produced",
    ),
    110: SukshmamshaInfo(
        index=110,
        nakshatra='Bharani',
        pada=2,
        nakshatra_pada='Bharani-2',
        name_sa='पापांश',
        name_en='Pāpāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Sinful",
    ),
    111: SukshmamshaInfo(
        index=111,
        nakshatra='Bharani',
        pada=3,
        nakshatra_pada='Bharani-3',
        name_sa='उग्रांश',
        name_en='Ugrāṁśa',
        nature=SukshmamshaNature.INAUSPICIOUS,
        meaning="Fierce",
    ),
    112: SukshmamshaInfo(
        index=112,
        nakshatra='Bharani',
        pada=4,
        nakshatra_pada='Bharani-4',
        name_sa='शुभांश',
        name_en='Śubhāṁśa',
        nature=SukshmamshaNature.AUSPICIOUS,
        meaning="Auspicious",
    ),
}

SUKSHMAMSHA_BY_NAK_PADA: Final[dict[str, SukshmamshaInfo]] = {
    info.nakshatra_pada.lower(): info for info in SUKSHMAMSHA_BY_INDEX.values()
}


def get_sukshmamsha(pada112: int) -> SukshmamshaInfo:
    """Return Sukshmamsha info for a 1-based Pada112 index (1..112)."""
    if pada112 not in SUKSHMAMSHA_BY_INDEX:
        raise ValueError(f"pada112 must be between 1 and 112; got {pada112}")
    return SUKSHMAMSHA_BY_INDEX[pada112]


def get_sukshmamsha_by_nak_pada(nakshatra: str, pada: int) -> SukshmamshaInfo:
    """Return Sukshmamsha info for a given Nakshatra and Pada (1..4)."""
    key = f'{nakshatra.strip().lower()}-{pada}'
    if key in SUKSHMAMSHA_BY_NAK_PADA:
        return SUKSHMAMSHA_BY_NAK_PADA[key]
    raise ValueError(f"Unknown nakshatra/pada combination: {nakshatra}-{pada}")


def is_auspicious_sukshmamsha(pada112: int) -> bool:
    """Check if the given Pada112 carries an auspicious nature."""
    return get_sukshmamsha(pada112).nature == SukshmamshaNature.AUSPICIOUS


def is_inauspicious_sukshmamsha(pada112: int) -> bool:
    """Check if the given Pada112 carries an inauspicious nature."""
    return get_sukshmamsha(pada112).nature == SukshmamshaNature.INAUSPICIOUS
