/** PdfExporter.tsx — opens a print-friendly report in a new tab so the user
 * can "Save as PDF" via the browser's native print dialog. No PDF library
 * dependency is installed in this project, so this is the honest, working
 * approach rather than pretending to generate a PDF file directly. */
import type { ComparedChart } from './ComparisonWorkspace';

interface PlanetRow {
  planet: string;
  cells: ({ rashi: string; house: number; degree: number; retro: boolean } | null)[];
  highlight: string;
}

interface ComparisonPdfData {
  charts: ComparedChart[];
  planetRows: PlanetRow[];
  sameSignPercent: number;
  differingPlanets: string[];
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildReportHtml(data: ComparisonPdfData): string {
  const { charts, planetRows, sameSignPercent, differingPlanets } = data;
  const names = charts.map((c) => escapeHtml(c.name));

  const planetRowsHtml = planetRows
    .map((row) => {
      const cells = row.cells
        .map((c) => `<td style="padding:0.5rem;">${c ? `${escapeHtml(c.rashi)} ${c.degree.toFixed(1)}°${c.retro ? ' (R)' : ''}` : '—'}</td>`)
        .join('');
      const badgeColor =
        row.highlight === 'exact' ? '#16a34a' : row.highlight === 'similar' ? '#ca8a04' : '#dc2626';
      const badgeLabel = row.highlight === 'exact' ? '✓ Same' : row.highlight === 'similar' ? '≈ Similar' : '✗ Different';
      return `<tr style="border-bottom:1px solid #e0e0e0;">
        <td style="padding:0.5rem;font-weight:500;">${escapeHtml(row.planet)}</td>
        ${cells}
        <td style="padding:0.5rem;"><span style="color:${badgeColor};font-weight:600;font-size:0.8rem;">${badgeLabel}</span></td>
      </tr>`;
    })
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>AstroOS Comparison Report</title>
<style>
  body { font-family: system-ui, sans-serif; padding: 2rem; max-width: 8.5in; margin: 0 auto; color: #1a1a2e; }
  h1, h2 { color: #1e1e8a; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #f0f4ff; text-align: left; padding: 0.5rem; }
  @media print { body { padding: 0.5in; } }
</style>
</head>
<body>
  <header style="border-bottom:2px solid #1e1e8a;padding-bottom:1rem;margin-bottom:2rem;">
    <h1 style="margin:0;">AstroOS Comparison Report</h1>
    <p style="margin:0.5rem 0 0;color:#5a6b80;">${names.join(' vs ')}</p>
  </header>

  <section style="margin-bottom:2rem;">
    <h2 style="border-bottom:1px solid #c3d0ff;padding-bottom:0.5rem;">Planet Comparison</h2>
    <table>
      <thead>
        <tr>
          <th>Planet</th>
          ${names.map((n) => `<th>${n}</th>`).join('')}
          <th>Match</th>
        </tr>
      </thead>
      <tbody>${planetRowsHtml}</tbody>
    </table>
  </section>

  <section style="margin-bottom:2rem;">
    <h2 style="border-bottom:1px solid #c3d0ff;padding-bottom:0.5rem;">Summary</h2>
    <div style="background:#f9f9f9;padding:1rem;border-radius:0.5rem;">
      <p><strong>Same-sign rate:</strong> ${sameSignPercent}%</p>
      <p><strong>Differing placements:</strong> ${differingPlanets.length ? differingPlanets.map(escapeHtml).join(', ') : 'None'}</p>
    </div>
  </section>

  <footer style="border-top:1px solid #c3d0ff;padding-top:1rem;color:#5a6b80;font-size:0.875rem;">
    <p>Generated by AstroOS</p>
  </footer>
</body>
</html>`;
}

export function exportComparisonToPdf(data: ComparisonPdfData): void {
  const win = window.open('', '_blank');
  if (!win) {
    alert('Please allow pop-ups for this site to export a PDF.');
    return;
  }
  win.document.write(buildReportHtml(data));
  win.document.close();
  win.onload = () => {
    win.focus();
    win.print();
  };
}
