"""
AstroOS — Tiered Reports API Router (Phase 10)

Endpoints:
  - POST /api/v1/reports/tiered/generate — Generate tiered narrative report (Free 2-pg, Pro 5-pg, Research dossier)
  - GET  /api/v1/reports/tiered/history  — View generated report history
  - GET  /api/v1/reports/tiered/{id}/download — Download generated report
"""

from __future__ import annotations

from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from sqlalchemy.ext.asyncio import AsyncSession

from apps.api.dependencies import get_current_user_from_bearer, get_db_session
from apps.api.domain.user import User
from apps.api.repositories.report_history_repository import ReportHistoryRepository
from apps.api.schemas.report_tiered import (
    GenerateTieredReportRequest,
    TieredReportHistoryResponse,
    TieredReportItemResponse,
)
from apps.api.services.tiered_report_service import TieredReportService

router = APIRouter(prefix="/api/v1", tags=["Tiered Reports"])


def _svc(db: AsyncSession) -> TieredReportService:
    return TieredReportService(db)


@router.post("/reports/tiered/generate", response_model=TieredReportItemResponse)
async def generate_tiered_report(
    body: GenerateTieredReportRequest,
    user: User = Depends(get_current_user_from_bearer),
    db: AsyncSession = Depends(get_db_session),
):
    """Generate a tiered narrative report with plan entitlement verification."""
    return await _svc(db).generate_report(user, body)


@router.get("/reports/tiered/history", response_model=TieredReportHistoryResponse)
async def get_report_history(
    limit: int = Query(20, ge=1, le=50),
    offset: int = Query(0, ge=0),
    user: User = Depends(get_current_user_from_bearer),
    db: AsyncSession = Depends(get_db_session),
):
    """Retrieve history of reports generated by the authenticated user."""
    user_id_val = user.id.value if hasattr(user.id, "value") else user.id
    user_uuid = UUID(str(user_id_val))
    items = await ReportHistoryRepository.list_by_user(db, user_uuid, limit=limit, offset=offset)
    total = await ReportHistoryRepository.count_by_user(db, user_uuid)
    return TieredReportHistoryResponse(
        items=[TieredReportItemResponse.model_validate(i) for i in items],
        total=total,
    )


@router.get("/reports/tiered/{report_id}/download")
async def download_tiered_report(
    report_id: UUID,
    db: AsyncSession = Depends(get_db_session),
):
    """Stream / download generated report document."""
    record = await ReportHistoryRepository.get_by_id(db, report_id)
    if record is None or not record.document_content:
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail="Report not found or expired.")

    content = record.document_content
    filename = f"AstroOS_{record.report_tier}_{record.subject_name.replace(' ', '_')}.html"
    return Response(
        content=content,
        media_type="text/html",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
