"""
Precision tests: planetary position accuracy.

Validates that the Swiss Ephemeris wrapper produces positions within
< 1 arc-second of golden references computed from pyswisseph 2.10.03
with official .se1 data files (seas_18.se1, semo_18.se1, sepl_18.se1).

Golden references were generated by calling swe.calc_ut() directly and
are hardcoded below. If the .se1 files change (e.g. user installs a
different version), these tests will catch the drift.

Also validates that Moshier fallback positions are within a known
tolerance band (< 7 arc-seconds for most planets; Rahu/Ketu may be
less precise due to node interpolation).
"""

from __future__ import annotations

import os
from datetime import datetime, timezone

import pytest
import swisseph as swe

from apps.api.domain.horoscope import D1Chart
from apps.api.services.horoscope_engine import HoroscopeEngine

# ---------------------------------------------------------------------------
# Golden reference data (pyswisseph 2.10.03 + official .se1 files)
# ---------------------------------------------------------------------------

# Test Case 1: 2000-01-07 13:30:00 UTC, Delhi (28.6139 N, 77.2090 E)
# JD = 2451551.0632428704

_GOLDEN_TROPICAL_CASE1 = {
    "sun":     286.550948,
    "moon":    295.323407,
    "mars":    332.666250,
    "mercury": 281.429053,
    "jupiter": 25.561668,
    "venus":   248.915698,
    "saturn":  40.308694,
    "rahu":    123.656934,
}

_GOLDEN_AYANAMSA_CASE1 = 23.857324

_GOLDEN_SIDEREAL_CASE1 = {
    "sun":     262.693624,
    "moon":    271.466083,
    "mars":    308.808926,
    "mercury": 257.571728,
    "jupiter": 1.704343,
    "venus":   225.058374,
    "saturn":  16.451370,
    "rahu":    99.799610,
    "ketu":    279.799610,
}

_GOLDEN_DECLINATIONS_CASE1 = {
    "sun":     -22.412376,
    "moon":    -20.318303,
    "mars":    -11.448372,
    "mercury": -24.463068,
    "jupiter": 8.735337,
    "venus":   -19.932976,
    "saturn":  12.615550,
    "rahu":    19.334135,
    "ketu":    -19.334135,
}

_GOLDEN_ASC_SIDEREAL_CASE1 = 101.054435

# Test Case 2: 2020-07-15 06:30:00 UTC, New York (40.7128 N, 74.0060 W)

_GOLDEN_SIDEREAL_CASE2 = {
    "sun":     89.090408,
    "moon":    24.291456,
    "mars":    345.775720,
    "mercury": 71.724891,
    "jupiter": 268.073151,
    "venus":   47.740967,
    "saturn":  274.914915,
    "rahu":    64.789335,
    "ketu":    244.789335,
}

_GOLDEN_ASC_SIDEREAL_CASE2 = 45.063008

# Moshier vs .se1 arc-second differences (pre-measured)
_MOSHIER_TOLERANCE_ARCSEC = {
    "sun":     0.02,
    "moon":    0.02,
    "mars":    0.06,
    "mercury": 0.01,
    "jupiter": 0.20,
    "venus":   0.05,
    "saturn":  0.08,
    "rahu":    7.0,
    "ketu":    7.0,
}

_ARCSEC_TOLERANCE = 1.0  # 1 arc-second for official .se1
_DMS_ARCSEC = 3600.0     # conversion factor


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _deg_to_arcsec(diff: float) -> float:
    """Angular difference in degrees to arc-seconds."""
    return abs(diff) * _DMS_ARCSEC


def _check_se1_available() -> bool:
    """Return True if official .se1 files are present."""
    eph_path = os.environ.get("EPHEMERIS_PATH", "")
    if not eph_path:
        # Try default relative path
        from pathlib import Path
        eph_path = str(Path(__file__).resolve().parents[2] / "data" / "ephemeris")
    if not os.path.isdir(eph_path):
        return False
    return any(f.endswith(".se1") for f in os.listdir(eph_path))


# ---------------------------------------------------------------------------
# Test: Tropical position accuracy with .se1
# ---------------------------------------------------------------------------

class TestTropicalPositions:
    """Validate tropical ecliptic longitudes against golden references."""

    @pytest.mark.parametrize(
        "planet,expected",
        list(_GOLDEN_TROPICAL_CASE1.items()),
        ids=[p for p in _GOLDEN_TROPICAL_CASE1],
    )
    def test_tropical_position_case1(
        self, ephemeris_wrapper, planet: str, expected: float
    ):
        if not _check_se1_available():
            pytest.skip("Official .se1 files not available")

        jd = swe.utc_to_jd(2000, 1, 7, 13, 30, 0, swe.GREG_CAL)[0]
        pos = ephemeris_wrapper.get_planet_position(planet, jd)
        diff_arcsec = _deg_to_arcsec(pos.longitude - expected)
        assert diff_arcsec < _ARCSEC_TOLERANCE, (
            f"{planet} tropical longitude off by {diff_arcsec:.4f} arcsec "
            f"(got {pos.longitude:.6f}, expected {expected:.6f})"
        )


# ---------------------------------------------------------------------------
# Test: Sidereal position accuracy with .se1
# ---------------------------------------------------------------------------

class TestSiderealPositions:
    """Validate sidereal ecliptic longitudes (with Lahiri ayanamsa)."""

    @pytest.mark.parametrize(
        "planet,expected",
        list(_GOLDEN_SIDEREAL_CASE1.items()),
        ids=[p for p in _GOLDEN_SIDEREAL_CASE1],
    )
    def test_sidereal_position_case1(
        self, horoscope_engine, planet: str, expected: float
    ):
        if not _check_se1_available():
            pytest.skip("Official .se1 files not available")

        dt = datetime(2000, 1, 7, 13, 30, 0, tzinfo=timezone.utc)
        chart = horoscope_engine.generate_d1(
            dt, latitude=28.6139, longitude=77.2090,
            ayanamsa="lahiri", house_system="W",
        )
        planet_pos = next(p for p in chart.planets if p.planet == planet)
        diff_arcsec = _deg_to_arcsec(planet_pos.sidereal_longitude - expected)
        assert diff_arcsec < _ARCSEC_TOLERANCE, (
            f"{planet} sidereal longitude off by {diff_arcsec:.4f} arcsec "
            f"(got {planet_pos.sidereal_longitude:.6f}, expected {expected:.6f})"
        )

    @pytest.mark.parametrize(
        "planet,expected",
        list(_GOLDEN_SIDEREAL_CASE2.items()),
        ids=[p for p in _GOLDEN_SIDEREAL_CASE2],
    )
    def test_sidereal_position_case2(
        self, horoscope_engine, planet: str, expected: float
    ):
        if not _check_se1_available():
            pytest.skip("Official .se1 files not available")

        dt = datetime(2020, 7, 15, 6, 30, 0, tzinfo=timezone.utc)
        chart = horoscope_engine.generate_d1(
            dt, latitude=40.7128, longitude=-74.0060,
            ayanamsa="lahiri", house_system="W",
        )
        planet_pos = next(p for p in chart.planets if p.planet == planet)
        diff_arcsec = _deg_to_arcsec(planet_pos.sidereal_longitude - expected)
        assert diff_arcsec < _ARCSEC_TOLERANCE, (
            f"{planet} sidereal longitude off by {diff_arcsec:.4f} arcsec "
            f"(got {planet_pos.sidereal_longitude:.6f}, expected {expected:.6f})"
        )


# ---------------------------------------------------------------------------
# Test: Ayanamsa accuracy
# ---------------------------------------------------------------------------

class TestAyanamsa:
    """Validate Lahiri ayanamsa value."""

    def test_lahiri_ayanamsa_case1(self, ephemeris_wrapper):
        if not _check_se1_available():
            pytest.skip("Official .se1 files not available")

        jd = swe.utc_to_jd(2000, 1, 7, 13, 30, 0, swe.GREG_CAL)[0]
        ayan = ephemeris_wrapper.get_ayanamsa(jd)
        diff_arcsec = _deg_to_arcsec(ayan - _GOLDEN_AYANAMSA_CASE1)
        assert diff_arcsec < _ARCSEC_TOLERANCE, (
            f"Lahiri ayanamsa off by {diff_arcsec:.4f} arcsec "
            f"(got {ayan:.6f}, expected {_GOLDEN_AYANAMSA_CASE1:.6f})"
        )


# ---------------------------------------------------------------------------
# Test: Ascendant accuracy
# ---------------------------------------------------------------------------

class TestAscendant:
    """Validate sidereal ascendant computation."""

    def test_ascendant_sidereal_case1(self, horoscope_engine):
        if not _check_se1_available():
            pytest.skip("Official .se1 files not available")

        dt = datetime(2000, 1, 7, 13, 30, 0, tzinfo=timezone.utc)
        chart = horoscope_engine.generate_d1(
            dt, latitude=28.6139, longitude=77.2090,
            ayanamsa="lahiri", house_system="W",
        )
        diff_arcsec = _deg_to_arcsec(
            chart.ascendant.sidereal_longitude - _GOLDEN_ASC_SIDEREAL_CASE1
        )
        assert diff_arcsec < _ARCSEC_TOLERANCE, (
            f"Ascendant sidereal off by {diff_arcsec:.4f} arcsec "
            f"(got {chart.ascendant.sidereal_longitude:.6f}, "
            f"expected {_GOLDEN_ASC_SIDEREAL_CASE1:.6f})"
        )

    def test_ascendant_sidereal_case2(self, horoscope_engine):
        if not _check_se1_available():
            pytest.skip("Official .se1 files not available")

        dt = datetime(2020, 7, 15, 6, 30, 0, tzinfo=timezone.utc)
        chart = horoscope_engine.generate_d1(
            dt, latitude=40.7128, longitude=-74.0060,
            ayanamsa="lahiri", house_system="W",
        )
        diff_arcsec = _deg_to_arcsec(
            chart.ascendant.sidereal_longitude - _GOLDEN_ASC_SIDEREAL_CASE2
        )
        assert diff_arcsec < _ARCSEC_TOLERANCE, (
            f"Ascendant sidereal off by {diff_arcsec:.4f} arcsec "
            f"(got {chart.ascendant.sidereal_longitude:.6f}, "
            f"expected {_GOLDEN_ASC_SIDEREAL_CASE2:.6f})"
        )


# ---------------------------------------------------------------------------
# Test: Declination accuracy
# ---------------------------------------------------------------------------

class TestDeclinations:
    """Validate equatorial declinations."""

    @pytest.mark.parametrize(
        "planet,expected",
        list(_GOLDEN_DECLINATIONS_CASE1.items()),
        ids=[p for p in _GOLDEN_DECLINATIONS_CASE1],
    )
    def test_declination_case1(self, ephemeris_wrapper, planet: str, expected: float):
        if not _check_se1_available():
            pytest.skip("Official .se1 files not available")

        jd = swe.utc_to_jd(2000, 1, 7, 13, 30, 0, swe.GREG_CAL)[0]
        decl = ephemeris_wrapper.get_declination(planet, jd)
        diff_arcsec = _deg_to_arcsec(decl - expected)
        assert diff_arcsec < _ARCSEC_TOLERANCE, (
            f"{planet} declination off by {diff_arcsec:.4f} arcsec "
            f"(got {decl:.6f}, expected {expected:.6f})"
        )


# ---------------------------------------------------------------------------
# Test: Moshier fallback precision
# ---------------------------------------------------------------------------

class TestMoshierFallback:
    """
    Validate that Moshier fallback produces positions within known
    tolerance of official .se1. Also validates graceful degradation
    (no exceptions, results are usable).
    """

    def test_moshier_fallback_no_exception(self):
        """Moshier mode must not raise even without .se1 files."""
        swe.set_ephe_path("")  # No ephemeris files
        swe.set_sid_mode(swe.SIDM_LAHIRI, 0, 0)
        jd = swe.utc_to_jd(2000, 1, 7, 13, 30, 0, swe.GREG_CAL)[0]

        xx, retflag = swe.calc_ut(jd, swe.SUN, swe.FLG_SWIEPH | swe.FLG_SPEED)
        assert retflag >= 0, "Moshier fallback returned error"
        assert xx[0] > 0, "Moshier Sun longitude must be positive"
        # Restore path
        swe.set_ephe_path(os.environ.get("EPHEMERIS_PATH", ""))

    def test_moshier_fallback_within_tolerance(self, ephemeris_wrapper):
        """Moshier positions must be within pre-measured tolerance of .se1."""
        if not _check_se1_available():
            pytest.skip("Official .se1 files not available for comparison")

        jd = swe.utc_to_jd(2000, 1, 7, 13, 30, 0, swe.GREG_CAL)[0]
        swe.set_ephe_path("")  # Force Moshier
        swe.set_sid_mode(swe.SIDM_LAHIRI, 0, 0)

        planet_ids = {
            "sun": swe.SUN, "moon": swe.MOON, "mars": swe.MARS,
            "mercury": swe.MERCURY, "jupiter": swe.JUPITER,
            "venus": swe.VENUS, "saturn": swe.SATURN,
        }

        swe.set_ephe_path("")  # Moshier
        for name, pid in planet_ids.items():
            xx_mos, _ = swe.calc_ut(jd, pid, swe.FLG_MOSEPH | swe.FLG_SPEED)
            # Restore and get official
            swe.set_ephe_path(os.environ.get("EPHEMERIS_PATH", ""))
            swe.set_sid_mode(swe.SIDM_LAHIRI, 0, 0)
            xx_off, _ = swe.calc_ut(jd, pid, swe.FLG_SWIEPH | swe.FLG_SPEED)

            diff_arcsec = abs(xx_off[0] - xx_mos[0]) * 3600.0
            tolerance = _MOSHIER_TOLERANCE_ARCSEC[name]
            assert diff_arcsec < tolerance, (
                f"{name} Moshier vs .se1 diff {diff_arcsec:.4f} arcsec "
                f"exceeds tolerance {tolerance}"
            )
            # Reset for next iteration
            swe.set_ephe_path("")

    def test_moshier_version_warning_message(self):
        """Verify that running without .se1 produces a detectable condition."""
        swe.set_ephe_path("")
        swe.set_sid_mode(swe.SIDM_LAHIRI, 0, 0)
        jd = swe.utc_to_jd(2000, 1, 7, 13, 30, 0, swe.GREG_CAL)[0]
        xx, retflag = swe.calc_ut(jd, swe.SUN, swe.FLG_SWIEPH | swe.FLG_SPEED)
        is_moshier = bool(retflag & swe.FLG_MOSEPH)
        assert is_moshier, "Expected Moshier mode when no .se1 files available"
        # Restore
        swe.set_ephe_path(os.environ.get("EPHEMERIS_PATH", ""))
        swe.set_sid_mode(swe.SIDM_LAHIRI, 0, 0)


# ---------------------------------------------------------------------------
# Test: Ephemeris service status detection
# ---------------------------------------------------------------------------

class TestEphemerisServiceStatus:
    """Validate that EphemerisService correctly detects .se1 vs Moshier."""

    def test_service_detects_official_mode(self, ephemeris_path):
        from apps.api.services.ephemeris_service import EphemerisService, EphemerisMode

        svc = EphemerisService(ephemeris_path)
        svc.initialize()
        status = svc.get_status()
        assert status.mode == EphemerisMode.OFFICIAL, (
            f"Expected OFFICIAL mode, got {status.mode}"
        )
        assert status.official_data is True
        assert len(status.se1_files) >= 3, (
            f"Expected at least 3 .se1 files, got {len(status.se1_files)}"
        )

    def test_service_detects_moshier_mode(self):
        from apps.api.services.ephemeris_service import EphemerisService, EphemerisMode

        svc = EphemerisService("/nonexistent/path")
        svc.initialize()
        status = svc.get_status()
        assert status.mode == EphemerisMode.MOSHIER, (
            f"Expected MOSHIER mode, got {status.mode}"
        )
        assert status.official_data is False
