"""
AES-256-GCM Session Encryption — RTCollab Phase IV (ADR-RTC-001, Milestone 5)

Each collaboration session gets a random 256-bit key, generated by the
session coordinator (the device that created the session) and handed to
peers once, in the WebSocket "welcome" message, over the LAN-trust
transport the ADR already assumes (TLS-disabled, LAN-only). Every
subsequent message body is AES-256-GCM sealed with that key before being
sent over the wire, so a passive observer on the LAN — anyone other than
the devices actually in the session — cannot read chart/yoga/chat content.

This does not defend against the coordinator itself (a session member's own
device), which is the trust boundary the ADR draws: local-first means data
never leaves the LAN/session, not that the host is untrusted by its own
peers.
"""

import base64
import json
import os
from typing import Any

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

KEY_SIZE_BYTES = 32  # 256-bit key
NONCE_SIZE_BYTES = 12  # 96-bit nonce, standard for GCM


def generate_session_key() -> bytes:
    return AESGCM.generate_key(bit_length=256)


def key_to_b64(key: bytes) -> str:
    return base64.b64encode(key).decode("ascii")


def key_from_b64(key_b64: str) -> bytes:
    return base64.b64decode(key_b64)


def encrypt_json(key: bytes, payload: dict[str, Any]) -> dict[str, str]:
    """Seal a JSON-serializable payload. Returns an envelope safe to send_json()."""
    aesgcm = AESGCM(key)
    nonce = os.urandom(NONCE_SIZE_BYTES)
    plaintext = json.dumps(payload).encode("utf-8")
    ciphertext = aesgcm.encrypt(nonce, plaintext, associated_data=None)
    return {
        "type": "encrypted",
        "nonce": base64.b64encode(nonce).decode("ascii"),
        "ciphertext": base64.b64encode(ciphertext).decode("ascii"),
    }


def decrypt_json(key: bytes, envelope: dict[str, Any]) -> dict[str, Any]:
    """Open an envelope produced by `encrypt_json`. Raises on tampered/wrong-key data."""
    aesgcm = AESGCM(key)
    nonce = base64.b64decode(envelope["nonce"])
    ciphertext = base64.b64decode(envelope["ciphertext"])
    plaintext = aesgcm.decrypt(nonce, ciphertext, associated_data=None)
    return json.loads(plaintext)


def is_encrypted_envelope(message: dict[str, Any]) -> bool:
    return message.get("type") == "encrypted" and "nonce" in message and "ciphertext" in message
