"""
AstroOS — Supervised Fine-Tuning (SFT) Playbook for Kundli LLM
=============================================================
Fine-tunes Meta-Llama-3.1-8B-Instruct or Qwen-2.5-7B-Instruct with QLoRA (4-bit)
using Unsloth for ultra-fast, memory-efficient training on Google Colab or local GPU.

Dataset: data/kundli_llm_sft_dataset.jsonl (generated by generate_kundli_llm_dataset.py)
"""

import os
import torch

try:
    from unsloth import FastLanguageModel
    from trl import SFTTrainer
    from transformers import TrainingArguments
    from datasets import load_dataset
except ImportError:
    print("[!] Unsloth or TRL not installed. To install in Colab or Linux environment:")
    print("    pip install \"unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git\"")
    print("    pip install --no-deps trl peft accelerate bitsandbytes")


def run_training(
    base_model_name: str = "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit",
    dataset_path: str = "data/kundli_llm_sft_dataset.jsonl",
    output_dir: str = "models/astroos-kundli-8b-lora",
    max_seq_length: int = 2048,
    num_epochs: int = 3,
    learning_rate: float = 2e-4,
):
    print(f"[+] Loading base model: {base_model_name}")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=base_model_name,
        max_seq_length=max_seq_length,
        dtype=None,  # Auto-detects float16 for Tesla T4, bfloat16 for Ampere+
        load_in_4bit=True,
    )

    print("[+] Configuring LoRA PEFT adapters...")
    model = FastLanguageModel.get_peft_model(
        model,
        r=16,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=16,
        lora_dropout=0.0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=42,
    )

    print(f"[+] Loading dataset from {dataset_path}...")
    dataset = load_dataset("json", data_files=dataset_path, split="train")

    def formatting_prompts_func(examples):
        convos = examples["messages"]
        texts = [tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False) for convo in convos]
        return {"text": texts}

    dataset = dataset.map(formatting_prompts_func, batched=True)

    print("[+] Setting up Trainer...")
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=max_seq_length,
        dataset_num_proc=2,
        packing=False,
        args=TrainingArguments(
            per_device_train_batch_size=2,
            gradient_accumulation_steps=4,
            warmup_steps=10,
            num_train_epochs=num_epochs,
            learning_rate=learning_rate,
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=5,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=42,
            output_dir=output_dir,
            save_strategy="epoch",
        ),
    )

    print("[+] Starting Fine-Tuning...")
    trainer.train()

    print(f"[+] Saving fine-tuned LoRA model to {output_dir}...")
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)

    print("[+] Exporting merged 16-bit and GGUF models...")
    # Optional GGUF export for local or cloud inference
    model.save_pretrained_gguf(f"{output_dir}_gguf", tokenizer, quantization_method="q4_k_m")
    print(f"[✓] Training and export complete! GGUF saved at: {output_dir}_gguf")


if __name__ == "__main__":
    if torch.cuda.is_available():
        run_training()
    else:
        print("[!] CUDA GPU is required for QLoRA training.")
        print("    You can upload this script and data/kundli_llm_sft_dataset.jsonl directly to a free Google Colab (T4 GPU) notebook.")
