/**
 * AstroOS — Central 300+ Master Life Events & KP Formula Catalog
 * 
 * Provides an exhaustive, encyclopedic reference of human life events,
 * mapped to their Primary Trigger House (Main House) and Supporting/Manifestation Cusps.
 */

export interface MasterEventItem {
  id: string;
  name: string;
  category: string;
  mainHouse: string;
  supportingHouses: string[];
  detrimentalHouses?: string[];
  description: string;
  kpFormula: string;
  significatorKarakas?: string[];
}

export const MASTER_LIFE_EVENTS_CATALOG: MasterEventItem[] = [
  // --- A ---
  {
    id: "absconding",
    name: "Absconding / Missing from Home",
    category: "Legal & Crisis",
    mainHouse: "XII",
    supportingHouses: ["III", "VIII"],
    detrimentalHouses: ["II", "IV", "XI"],
    description: "Leaving family secretly, going into hiding or untraceable whereabouts.",
    kpFormula: "12th CSL (Separation/Exile) linked to 3rd (Short movement) and 8th (Secrecy/Trouble).",
    significatorKarakas: ["Rahu", "Saturn", "Moon"],
  },
  {
    id: "accident",
    name: "Accident (Physical Injury)",
    category: "Health & Accidents",
    mainHouse: "VIII",
    supportingHouses: ["I", "VI", "XII"],
    detrimentalHouses: ["V", "XI"],
    description: "Physical injury, vehicular collision or trauma.",
    kpFormula: "8th CSL (Accident/Sudden trauma) signifying 1st (Body), 6th (Injury), and 12th (Hospitalization).",
    significatorKarakas: ["Mars", "Rahu", "Saturn"],
  },
  {
    id: "accidental-death",
    name: "Accidental Death / Unnatural End",
    category: "Health & Accidents",
    mainHouse: "VIII",
    supportingHouses: ["I", "II", "VII", "XII"],
    description: "Critical fatality resulting from accidents or sudden trauma.",
    kpFormula: "8th CSL in star of Maraka (2, 7) and Badhaka lords, signifying 1, 8, 12.",
    significatorKarakas: ["Mars", "Saturn", "Rahu"],
  },
  {
    id: "accumulating-huge-wealth",
    name: "Accumulating Huge Wealth / Riches",
    category: "Finance & Wealth",
    mainHouse: "II",
    supportingHouses: ["VI", "XI"],
    detrimentalHouses: ["XII", "VIII", "V"],
    description: "Continuous inflow and aggregation of liquid assets and substantial wealth.",
    kpFormula: "2nd CSL strongly signifying House 2 (Assets), 6th (Income from service/business) and 11th (Gains).",
    significatorKarakas: ["Jupiter", "Venus", "Mercury"],
  },
  {
    id: "addiction-alcohol",
    name: "Addiction to Alcohol / Substances",
    category: "Health & Lifestyle",
    mainHouse: "VIII",
    supportingHouses: ["I", "V", "XII"],
    description: "Compulsive substance dependency and behavioral escapism.",
    kpFormula: "8th/12th CSL linked to afflicted Moon (Mind) or Venus/Rahu in House 2/5/12.",
    significatorKarakas: ["Rahu", "Moon", "Venus"],
  },
  {
    id: "adopt-a-child",
    name: "Adopt a Child",
    category: "Family & Progeny",
    mainHouse: "V",
    supportingHouses: ["VIII", "XII"],
    description: "Legal adoption of a non-biological son or daughter.",
    kpFormula: "5th CSL in star/sub of Mercury or Saturn, connected to 8th/12th houses (External origin).",
    significatorKarakas: ["Jupiter", "Mercury", "Saturn"],
  },
  {
    id: "always-sick",
    name: "Always Sick / Chronic Health Issues",
    category: "Health & Disease",
    mainHouse: "VI",
    supportingHouses: ["I", "VIII", "XII"],
    description: "Persistent recurring illnesses and low baseline vitality.",
    kpFormula: "1st CSL in star of 6th lord, and 6th CSL signifying 1, 6, 8, 12 continuously.",
    significatorKarakas: ["Saturn", "Sun", "Rahu"],
  },
  {
    id: "ancestral-property-getting",
    name: "Ancestral Property (Getting / Inheriting)",
    category: "Property & Wealth",
    mainHouse: "VIII",
    supportingHouses: ["II", "IV", "XI"],
    description: "Receiving inheritance, land, or estate from father/forefathers.",
    kpFormula: "8th CSL (Inheritance) signifying 4th (Land/House), 2nd (Wealth), and 11th (Gains).",
    significatorKarakas: ["Mars", "Saturn", "Jupiter"],
  },
  {
    id: "anticipated-promotion-delayed",
    name: "Anticipated Promotion (Delayed / Blocked)",
    category: "Career & Profession",
    mainHouse: "X",
    supportingHouses: ["V", "VIII"],
    detrimentalHouses: ["XI", "VI"],
    description: "Career elevation deferred due to internal politics or structural blockers.",
    kpFormula: "10th CSL signifying 5th (8th from 10th - setback) or 8th house, blocking 11th fulfillment.",
    significatorKarakas: ["Saturn", "Sun"],
  },
  {
    id: "astrologer",
    name: "Astrologer / Occult Practitioner",
    category: "Career & Profession",
    mainHouse: "VIII",
    supportingHouses: ["II", "IX", "X", "XI"],
    description: "Professional practice in Vedic/KP astrology, divination, or occult sciences.",
    kpFormula: "8th CSL (Occult) and 10th CSL (Career) connected to Mercury (Calculations) and Jupiter (Wisdom).",
    significatorKarakas: ["Mercury", "Jupiter", "Ketu"],
  },
  {
    id: "attainment-of-spirituality",
    name: "Attainment of Spirituality / Enlightenment",
    category: "Spirituality & Moksha",
    mainHouse: "IX",
    supportingHouses: ["V", "XII"],
    description: "Deep spiritual realization, guru grace, and liberation consciousness.",
    kpFormula: "9th CSL and 12th CSL in star of Ketu or Jupiter signifying Houses 5, 9, 12.",
    significatorKarakas: ["Ketu", "Jupiter", "Sun"],
  },

  // --- B ---
  {
    id: "bank-deposits",
    name: "Bank Deposits / Fixed Savings",
    category: "Finance & Wealth",
    mainHouse: "II",
    supportingHouses: ["XI"],
    description: "Opening fixed deposits, certificate of deposits, and long-term liquid reserves.",
    kpFormula: "2nd CSL connected to 11th house without 12th house leakage.",
    significatorKarakas: ["Jupiter", "Mercury"],
  },
  {
    id: "basic-education",
    name: "Basic Education up to Graduation",
    category: "Education & Academics",
    mainHouse: "IV",
    supportingHouses: ["IX", "XI"],
    detrimentalHouses: ["III", "VIII"],
    description: "Successful primary, secondary, and undergraduate university education.",
    kpFormula: "4th CSL (Schooling/Degree) signifying 9th (Higher studies) and 11th (Success).",
    significatorKarakas: ["Mercury", "Jupiter"],
  },
  {
    id: "boldness-take-job",
    name: "Boldness to Take a Job / Enter Career",
    category: "Career & Profession",
    mainHouse: "VI",
    supportingHouses: ["II", "X", "XI"],
    description: "Overcoming self-doubt and stepping decisively into competitive employment.",
    kpFormula: "3rd CSL (Courage) linked to 6th (Service) and 10th (Status).",
    significatorKarakas: ["Mars", "Sun"],
  },
  {
    id: "borrowing-repay-debt",
    name: "Borrowing to Repay Debt Due to Business",
    category: "Finance & Debt",
    mainHouse: "VI",
    supportingHouses: ["IX", "VI", "II"],
    description: "Refinancing commercial loans to cover operational deficits.",
    kpFormula: "6th CSL (Debts) in star of 6th/9th/2nd house significators.",
    significatorKarakas: ["Mercury", "Saturn", "Mars"],
  },
  {
    id: "break-education",
    name: "Break in Education / Academic Gap",
    category: "Education & Academics",
    mainHouse: "IV",
    supportingHouses: ["III", "VIII", "XII"],
    description: "Temporary drop out, failed semester, or forced study hiatus.",
    kpFormula: "4th CSL signifying 3rd (12th from 4th) + 8th (Obstacles) + 12th (Loss).",
    significatorKarakas: ["Rahu", "Saturn"],
  },
  {
    id: "break-in-service",
    name: "Break in Service / Job Layoff",
    category: "Career & Profession",
    mainHouse: "X",
    supportingHouses: ["V", "VIII", "XII"],
    description: "Temporary termination of employment, involuntary layoff, or bench period.",
    kpFormula: "10th CSL signifying 5th (negation of 6th) and 9th (negation of 10th) + 12th.",
    significatorKarakas: ["Saturn", "Rahu", "Mars"],
  },
  {
    id: "breaking-of-engagement",
    name: "Breaking of Engagement / Betrothal Call-off",
    category: "Marriage & Relationships",
    mainHouse: "VII",
    supportingHouses: ["VI", "XII"],
    description: "Call-off of arranged marriage or formal engagement prior to wedding.",
    kpFormula: "7th CSL in star of 6th (12th from 7th) or 12th house significator.",
    significatorKarakas: ["Mars", "Venus", "Rahu"],
  },
  {
    id: "buildings-constructed-for-renting",
    name: "Buildings Constructed for Renting Out",
    category: "Property & Real Estate",
    mainHouse: "IV",
    supportingHouses: ["VI", "XI", "XII"],
    description: "Erecting commercial or residential tenements for continuous rental income.",
    kpFormula: "4th CSL (Building) linked to 6th (Tenants/Rental rent) and 11th (Profits).",
    significatorKarakas: ["Mars", "Saturn", "Venus"],
  },

  // --- C ---
  {
    id: "caesarean-child-birth",
    name: "Caesarean Child Birth (C-Section)",
    category: "Family & Progeny",
    mainHouse: "V",
    supportingHouses: ["II", "VIII", "XI", "XII"],
    description: "Surgical operative delivery of infant.",
    kpFormula: "5th CSL (Child) and 8th CSL (Surgery) connected to Mars (Scalpel) and 12th (Hospital).",
    significatorKarakas: ["Mars", "Jupiter", "Ketu"],
  },
  {
    id: "coming-back-from-abroad",
    name: "Coming Back from Abroad (Repatriation)",
    category: "Travel & Relocation",
    mainHouse: "IV",
    supportingHouses: ["IX", "XI"],
    description: "Returning to homeland or native country after foreign stay.",
    kpFormula: "4th CSL (Homeland) signifying 9th (Return journey) and 11th (Successful return).",
    significatorKarakas: ["Moon", "Jupiter"],
  },
  {
    id: "commission-agency-business",
    name: "Commission Agency / Brokerage as Business",
    category: "Career & Profession",
    mainHouse: "X",
    supportingHouses: ["III", "VI", "XI"],
    description: "Operating commission brokerage, liaison consultancy, or middleman trading.",
    kpFormula: "10th CSL linked to 3rd (Commission/Agency/Mediation) + 6th and 11th.",
    significatorKarakas: ["Mercury", "Rahu", "Venus"],
  },
  {
    id: "competitive-exam",
    name: "Competitive Exam (Success / Selection)",
    category: "Education & Career",
    mainHouse: "VI",
    supportingHouses: ["IV", "IX", "XI"],
    detrimentalHouses: ["V", "VIII", "XII"],
    description: "Clearing government, civil services, or elite university entrance examinations.",
    kpFormula: "6th CSL (Competition/Victory over peers) signifying 4th (Knowledge), 9th (Higher exam) and 11th (Fulfillment).",
    significatorKarakas: ["Mercury", "Mars", "Sun", "Jupiter"],
  },
  {
    id: "computer-professional",
    name: "Computer Professional / IT Technologist",
    category: "Career & Profession",
    mainHouse: "X",
    supportingHouses: ["III", "VI", "XI"],
    description: "Software developer, hardware specialist, network engineer, or database architect.",
    kpFormula: "10th CSL in star of Mercury/Rahu connected to 3rd (Computers/Information) and 11th.",
    significatorKarakas: ["Mercury", "Rahu", "Mars"],
  },
  {
    id: "conflicts-in-marriage",
    name: "Conflicts in Marriage / Marital Discord",
    category: "Marriage & Relationships",
    mainHouse: "VII",
    supportingHouses: ["VI", "VIII", "XII"],
    description: "Recurrent arguments, emotional friction, or domestic incompatibility.",
    kpFormula: "7th CSL in star of 6th (Disputes/Litigation) or 8th (Mental agony) house lords.",
    significatorKarakas: ["Mars", "Rahu", "Venus"],
  },
  {
    id: "construct-a-house",
    name: "Construct a House / Own Residence",
    category: "Property & Real Estate",
    mainHouse: "IV",
    supportingHouses: ["XI", "XII"],
    detrimentalHouses: ["III", "VI"],
    description: "Building, purchasing, or acquiring residential home.",
    kpFormula: "4th CSL (Property) signifying 11th (Gain of asset) and 12th (Investment outflow).",
    significatorKarakas: ["Mars", "Venus", "Saturn"],
  },
  {
    id: "cure-disease-recovery",
    name: "Cure Disease / Full Medical Recovery",
    category: "Health & Recovery",
    mainHouse: "VI",
    supportingHouses: ["V", "XI"],
    detrimentalHouses: ["I", "VIII", "XII"],
    description: "Regaining physical vitality and overcoming acute or chronic medical ailments.",
    kpFormula: "6th CSL signifying 5th (12th from 6th - cure) and 11th (12th from 12th - recovery).",
    significatorKarakas: ["Jupiter", "Sun", "Moon"],
  },

  // --- D ---
  {
    id: "danger-to-health",
    name: "Danger to Health / Severe Infection",
    category: "Health & Disease",
    mainHouse: "VI",
    supportingHouses: ["VIII", "XII"],
    description: "Sudden onset of virulent illness requiring urgent medical intervention.",
    kpFormula: "6th CSL linked to 8th and 12th houses without 11th house protection.",
    significatorKarakas: ["Mars", "Rahu", "Saturn"],
  },
  {
    id: "delay-in-marriage",
    name: "Delay in Marriage / Late Wedding",
    category: "Marriage & Relationships",
    mainHouse: "VII",
    supportingHouses: ["I", "VI", "X", "XII"],
    description: "Marital union delayed beyond expected societal age bracket.",
    kpFormula: "7th CSL in star/sub of Saturn signifying 1, 6, 10 (negation of 2, 7, 11).",
    significatorKarakas: ["Saturn", "Sun"],
  },
  {
    id: "delivery-of-child",
    name: "Delivery of Child / Progeny Birth",
    category: "Family & Progeny",
    mainHouse: "V",
    supportingHouses: ["II", "XI"],
    detrimentalHouses: ["I", "IV", "X"],
    description: "Welcoming newborn child into the immediate family circle.",
    kpFormula: "5th CSL (Child) strongly signifying House 2 (Family expansion) and 11th (Joy/Fulfillment).",
    significatorKarakas: ["Jupiter", "Moon", "Venus"],
  },
  {
    id: "depression",
    name: "Depression & Nervous Exhaustion",
    category: "Health & Mind",
    mainHouse: "VI",
    supportingHouses: ["I", "VIII", "XII"],
    description: "Psychological despondency, anxiety, and neuro-chemical depletion.",
    kpFormula: "1st or 6th CSL in star of afflicted Moon/Mercury signifying 8th and 12th.",
    significatorKarakas: ["Moon", "Saturn", "Rahu"],
  },
  {
    id: "discharge-from-hospital",
    name: "Discharge from Hospital",
    category: "Health & Recovery",
    mainHouse: "XII",
    supportingHouses: ["V", "XI"],
    description: "Conclusion of inpatient clinical care and release to home.",
    kpFormula: "12th CSL (Hospitalization) signifying 11th (12th from 12th - end of hospitalization) + 5th.",
    significatorKarakas: ["Jupiter", "Sun"],
  },

  // --- L ---
  {
    id: "loss-in-investment",
    name: "Loss in Investment / Stock Depreciation",
    category: "Finance & Loss",
    mainHouse: "XII",
    supportingHouses: ["I", "V", "VIII"],
    description: "Severe capital destruction in speculative, business, or equity ventures.",
    kpFormula: "12th CSL (Loss) linked to 5th (Speculation) + 8th (Sudden crisis) and 1st (Personal bearing).",
    significatorKarakas: ["Rahu", "Mercury", "Mars"],
  },
];
